import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import { SearchTextForPokemonCardProvider } from "./contexts/searchTextForPokemonCard";
import Header from "./header";

// Load local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
  display: "swap",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
  display: "swap",
});

// Metadata for the layout
export const metadata: Metadata = {
  title: "Pokémon Types Chart",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SearchTextForPokemonCardProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header />
          {children}
        </body>
      </SearchTextForPokemonCardProvider>
    </html>
  );
}
